export default [
    [-1, "Which Programming Language?", "./assets/images/starter.png"],
    [0, "Why do you want to learn programming?", null],
    [1, "I don't know, just pick one for me?", null],
    [2, "Improve my self", null],
    [3, "I'm interested", null],
    [4, "Just for fun", null],
    [5, "For my kid", null],
    [6, "Make money", null],
    [7, "Start with scratch then move on to...", null],
    [8, "Get a job!", null],
    [9, "Which platform/field", null],
    [10, "I want to work for big tech companies", null],
    [11, "Facebook", null],
    [12, "Microsoft", null],
    [13, "Google", null],
    [14, "Apple", null],
    [15, "Doesn't matter, I just want $$$", "./assets/images/money.png"],
    [16, "Web", "./assets/images/web.png"],
    [17, "Front-end (Web interface)", null],
    [18, "Back-end (Brain behind a website)", null],
    [19, "I want to work for...", null],
    [20, "Corporate", null],
    [21, "What do you think about Microsoft?", "./assets/images/microsoft.png"],
    [22, "I'm a fan", null],
    [23, "Not bad", null],
    [24, "Suck", null],
    [25, "Startup", null],
    [26, "Do you want to try something new with huge potential, but less mature?", null],
    [27, "Which one is your favourite toy?", null],
    [28, "Lego", "./assets/images/lego.png"],
    [29, "Play-Doh", "./assets/images/play-doh.png"],
    [30, "I've an old & ugly toy, but I love it so much!", null],
    [31, "3D/Gaming", "/assetsimages/game.png"],
    [32, "Mobile", "/assetsimages/mobile.png"],
    [33, "Which OS?", null],
    [34, "iOS", null],
    [35, "Android", null],
    [36, "Enterprise", "./assets/images/enterprise.png"],
    [37, "I have a startup idea!", "./assets/images/lighter.png"],
    [38, "Does your app provides info in real-time, like Twitter?", null],
    [39, "Have a brilliant idea/platform in mind?", null],
    [40, "Nope, just want to get started", null],
    [41, "I prefer to learn things...", null],
    [42, "The easy way", null],
    [43, "The the best way", null],
    [44, "The slightly harder way", null],
    [45, "Auto manual car?", null],
    [46, "Auto", null],
    [47, "Manual", null],
    [48, "The really hard way (but easier to pick up other language in the future)", null],
    [100, "Yes", null],
    [101, "No", null],
    [102, "Not sure", null],
    [103, "Ready to know?", null],
    [1000, "Python", "./assets/images/python.png", 1],
    [1001, "C#", "./assets/images/csharp.png", 3],
    [1002, "Objective C", "./assets/images/oc.png", 3],
    [1003, "Java", "./assets/images/java.png", 3],
    [1004, "JavaScript", "./assets/images/js.png", 2],
    [1005, "PHP", "./assets/images/php.png", 2],
    [1006, "C++", "./assets/images/cpp.png", 4],
    [1007, "C", "./assets/images/c.png", 3],
    [1008, "Ruby", "./assets/images/ruby.png", 2]
];